#!/usr/bin/env node
/* Generates the self-contained dino-loader.js file:
 *   banner + t-rex-runner engine (auto-init removed) + auto-pilot driver,
 *   PNG sprites inlined as data-URIs → a single file, zero dependencies.
 *
 * Usage: node scripts/build.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const V = join(ROOT, 'vendor', 't-rex-runner');

// 1. Original Chromium engine, with the auto-instantiation removed
//    (the game must not start on its own on `.interstitial-wrapper`).
let engine = readFileSync(join(V, 'index.js'), 'utf8');
const before = engine.length;
engine = engine
  .replace(/function onDocumentLoad\(\)\s*\{[\s\S]*?\}\s*/, '')
  .replace(/document\.addEventListener\(\s*['"]DOMContentLoaded['"]\s*,\s*onDocumentLoad\s*\)\s*;?/, '');
if (engine.length === before) {
  console.error('⚠️  auto-init not found — the engine may have changed.');
  process.exit(1);
}

// 2. Sprites → data-URI
const dataUri = (p) =>
  'data:image/png;base64,' + readFileSync(join(V, p)).toString('base64');
const sprite1x = dataUri('assets/default_100_percent/100-offline-sprite.png');
const sprite2x = dataUri('assets/default_200_percent/200-offline-sprite.png');

// 3. Driver + sprite substitution
let driver = readFileSync(join(ROOT, 'src', 'dino-loader.driver.js'), 'utf8');
driver = driver.replace('__SPRITE_1X__', sprite1x).replace('__SPRITE_2X__', sprite2x);

// 4. Assembly
const banner = `/*!
 * dino-run-loader — a waiting/loading <dino-loader> Web Component.
 *
 * This project's own code (auto-pilot driver, Web Component wrapper, build
 * script, React wrapper) is licensed under the MIT License,
 * Copyright (c) 2026 Charles Boonen. See LICENSE.
 *
 * The dinosaur, the scenery and the jump animation are the Chrome
 * "T-Rex Runner" game, bundled from the Chromium project via
 * wayou/t-rex-runner, under the BSD 3-Clause License
 * (Copyright (c) 2014 The Chromium Authors; Copyright (c) 2022 牛さん).
 * Full text: NOTICE and vendor/t-rex-runner/LICENSE.
 *
 * Generated by scripts/build.mjs — do not edit by hand.
 */
`;

const out = banner + '\n' + engine + '\n' + driver + '\n';
writeFileSync(join(ROOT, 'dino-loader.js'), out);
console.log(`✓ dino-loader.js generated (${(out.length / 1024).toFixed(1)} KB, sprites inlined)`);
